#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.
menuentry "Custom GRUB Entry" {
	insmod gzio
	linux /boot/vmlinuz-4.19.0-13-amd64 net.ifnames=0 biosdevname=0 panic_stop root=/dev/vda1
	initrd /boot/custom/initrd.img.gz
}
